// src/tasks.js
export const initialTasks = [
  // --- 1단계: 호빗 ---
  { id: 1, step: 1, category: "호빗", subCategory: "마그네틱 열어두기", text: "비/바람 꺼내두기" },
  { id: 2, step: 1, category: "호빗", subCategory: "마그네틱 열어두기", text: "곡식창고" },
  { id: 3, step: 1, category: "호빗", subCategory: "마그네틱 열어두기", text: "불 곡식" },
  { id: 4, step: 1, category: "호빗", subCategory: "마그네틱 열어두기", text: "액자 (비옥한 흙 빼고 붙이지 말기)" },
  { id: 5, step: 1, category: "호빗", subCategory: "마그네틱 열어두기", text: "클라우드 디스크" },
  { id: 6, step: 1, category: "호빗", subCategory: "마그네틱 열어두기", text: "모래시계" },
  { id: 7, step: 1, category: "호빗", subCategory: "마그네틱 열어두기", text: "해 꺼내두기" },
  { id: 8, step: 1, category: "호빗", subCategory: "마그네틱 열어두기", text: "뒷방문" },
  { id: 9, step: 1, category: "호빗", subCategory: "자물쇠 잠그기", text: "뒷방 2개, 앞방 5개 잠그기" },
  { id: 10, step: 1, category: "호빗", subCategory: "장비 종료", text: "빔 프로젝터 종료하기" },
  { id: 11, step: 1, category: "호빗", subCategory: "장비 종료", text: "에어컨 송풍 전환" },

  // --- 2단계: 비폴로 ---
  { id: 12, step: 2, category: "비폴로", subCategory: "마그네틱 열어두기", text: "첫방 1개 삼각형" },
  { id: 13, step: 2, category: "비폴로", subCategory: "마그네틱 열어두기", text: "두번째방 4개" },
  { id: 14, step: 2, category: "비폴로", subCategory: "마그네틱 열어두기", text: "문 열어두기" },
  { id: 15, step: 2, category: "비폴로", subCategory: "자물쇠 잠그기", text: "방향자물쇠 잠그기" },
  { id: 16, step: 2, category: "비폴로", subCategory: "자물쇠 잠그기", text: "미니매그 잠그기" },
  { id: 17, step: 2, category: "비폴로", subCategory: "장비 종료", text: "에어컨 송풍 전환" },

  // --- 3단계: 마카오 ---
  { id: 18, step: 3, category: "마카오", subCategory: "자물쇠 잠그기", text: "첫방 MGF 0000초기화" },
  { id: 19, step: 3, category: "마카오", subCategory: "마그네틱 열어두기", text: "첫방 턴테이블 편지서랍" },
  { id: 20, step: 3, category: "마카오", subCategory: "마그네틱 열어두기", text: "선글라스 단계 열어두기" },
  { id: 21, step: 3, category: "마카오", subCategory: "마그네틱 열어두기", text: "두번째방 오른손 2개 서랍" },
  { id: 22, step: 3, category: "마카오", subCategory: "마그네틱 열어두기", text: "두번째방 카메라" },
  { id: 23, step: 3, category: "마카오", subCategory: "마그네틱 열어두기", text: "마지막 방 USB" },
  { id: 24, step: 3, category: "마카오", subCategory: "마그네틱 열어두기", text: "마지막 방 USB 아래서랍" },
  { id: 25, step: 3, category: "마카오", subCategory: "문 열어두기", text: "내부 문 2개 다 열기" },
  { id: 26, step: 3, category: "마카오", subCategory: "문 열어두기", text: "퇴장문 열어두기" },
  { id: 27, step: 3, category: "마카오", subCategory: "장비 종료", text: "두번째 방 티비 종료하기" },
  { id: 28, step: 3, category: "마카오", subCategory: "자물쇠 잠그기", text: "빨간 자물쇠 (턴테이블)" },
  { id: 29, step: 3, category: "마카오", subCategory: "자물쇠 잠그기", text: "두번째방 벽장 1개" },
  { id: 30, step: 3, category: "마카오", subCategory: "자물쇠 잠그기", text: "마지막방 캐비닛 1개" },
  { id: 31, step: 3, category: "마카오", subCategory: "장비 종료", text: "힌트폰 꺼내기" },
  { id: 32, step: 3, category: "마카오", subCategory: "장비 종료", text: "에어컨 송풍 전환" },
  { id: 33, step: 3, category: "마카오", subCategory: "기타", text: "조끼 확인" },

  // --- 4단계: 알비노 ---
  { id: 34, step: 4, category: "알비노", subCategory: "모니터 종료", text: "힌트 모니터 종료" },
  { id: 35, step: 4, category: "알비노", subCategory: "모니터 종료", text: "선반에 있는 모니 2개 종료" },
  { id: 36, step: 4, category: "알비노", subCategory: "모니터 종료", text: "뒷방 엔딩 모니터 1개 종료" },
  { id: 37, step: 4, category: "알비노", subCategory: "서랍 열어두기", text: "F, E, D 서랍 열어두기 (3개)" },
  { id: 38, step: 4, category: "알비노", subCategory: "마그네틱 열어두기", text: "SSCP 문" },
  { id: 39, step: 4, category: "알비노", subCategory: "마그네틱 열어두기", text: "A파일 꺼내두기" },
  { id: 40, step: 4, category: "알비노", subCategory: "마그네틱 열어두기", text: "출입 문" },
  { id: 41, step: 4, category: "알비노", subCategory: "자물쇠 잠그기", text: "첫방 열쇠자물쇠" },
  { id: 42, step: 4, category: "알비노", subCategory: "자물쇠 잠그기", text: "뒷방 SMYUO" },
  { id: 43, step: 4, category: "알비노", subCategory: "장비 초기화", text: "969 장치 초기화" },
  { id: 44, step: 4, category: "알비노", subCategory: "장비 초기화", text: "비상전력 장치 초기화" },
  { id: 45, step: 4, category: "알비노", subCategory: "장비 종료", text: "인큐베이터 전원 끄고 열어두기" },
  { id: 46, step: 4, category: "알비노", subCategory: "장비 종료", text: "뒷방 스탠드 끄기" },
  { id: 47, step: 4, category: "알비노", subCategory: "장비 종료", text: "에어컨 송풍 전환" },

  // --- 5단계: 레테 ---
  { id: 48, step: 5, category: "레테", subCategory: "장비 종료", text: "빔 종료 (리모컨 꺼내두기)" },
  { id: 49, step: 5, category: "레테", subCategory: "마그네틱 열어두기", text: "과녁판" },
  { id: 50, step: 5, category: "레테", subCategory: "마그네틱 열어두기", text: "열쇠 붙이지 말기" },
  { id: 51, step: 5, category: "레테", subCategory: "마그네틱 열어두기", text: "와인병 (전화기 아래)" },
  { id: 52, step: 5, category: "레테", subCategory: "마그네틱 열어두기", text: "ROSE" },
  { id: 53, step: 5, category: "레테", subCategory: "마그네틱 열어두기", text: "퇴장문" },
  { id: 54, step: 5, category: "레테", subCategory: "자물쇠 잠그기", text: "505" },
  { id: 55, step: 5, category: "레테", subCategory: "자물쇠 잠그기", text: "와인&명함" },
  { id: 56, step: 5, category: "레테", subCategory: "자물쇠 잠그기", text: "책" },
  { id: 57, step: 5, category: "레테", subCategory: "자물쇠 잠그기", text: "시간 시계는 열어두기" },
  { id: 58, step: 5, category: "레테", subCategory: "자물쇠 잠그기", text: "자물쇠 시계는 닫기" },
  { id: 59, step: 5, category: "레테", subCategory: "자물쇠 잠그기", text: "JACK" },
  { id: 60, step: 5, category: "레테", subCategory: "자물쇠 잠그기", text: "941생" },
  { id: 61, step: 5, category: "레테", subCategory: "장비 종료", text: "에어컨 송풍 전환" },

  // --- 6단계: 공통 시설 및 장비 ---
  { id: 62, step: 6, category: "공통시설", subCategory: "에어컨/환풍기", text: "모든 테마 송풍 확인 및 1시간 예약 걸기" },
  { id: 63, step: 6, category: "공통시설", subCategory: "에어컨/환풍기", text: "환풍기 모두 끄기 (호빗, 레테 위치 다름 체크)" },
  { id: 64, step: 6, category: "공통시설", subCategory: "에어컨/환풍기", text: "환풍기 끄기 (비폴로, 마카오, 알비노)" },
  { id: 65, step: 6, category: "공통시설", subCategory: "빔 프로젝터", text: "빔 끄기 2중 체크 (호빗)" },
  { id: 66, step: 6, category: "공통시설", subCategory: "빔 프로젝터", text: "빔 끄기 2중 체크 (레테)" },
  { id: 67, step: 6, category: "공통시설", subCategory: "특수장비", text: "호빗 마법서 코드로 종료" },
  { id: 68, step: 6, category: "공통시설", subCategory: "특수장비", text: "호빗 마법서 전원 코드 뽑기" },
  { id: 69, step: 6, category: "공통시설", subCategory: "테마 PC 종료", text: "모든 테마 모니터 불끄기" },
  { id: 70, step: 6, category: "공통시설", subCategory: "테마 PC 종료", text: "호빗, 레테, 알비노, 마카오 PC 종료(shutdown)" },
  { id: 71, step: 6, category: "공통시설", subCategory: "테마 PC 종료", text: "비터치 PC 직접 끄기" },
  { id: 72, step: 6, category: "공통시설", subCategory: "테마 PC 종료", text: "비폴로 PC 직접 끄기" },
  { id: 73, step: 6, category: "공통시설", subCategory: "비품관리", text: "종이컵 없으면 채우기" },

  // --- 7단계: 매장 정리 및 서류 정산 ---
  { id: 74, step: 7, category: "매장정산", subCategory: "전자기기 마감", text: "모든 휴대폰 전원 OFF 및 충전 확인" },
  { id: 75, step: 7, category: "매장정산", subCategory: "전자기기 마감", text: "배터리 부족 기기는 다음날 시트에 메모" },
  { id: 76, step: 7, category: "매장정산", subCategory: "홀 마감", text: "동의서 숨기기" },
  { id: 77, step: 7, category: "매장정산", subCategory: "전자기기 마감", text: "무전기 전원 끄고 충전기 꽂기" },
  { id: 78, step: 7, category: "매장정산", subCategory: "홀 마감", text: "외부 입간판 매장 안으로 올리기" },
  { id: 79, step: 7, category: "매장정산", subCategory: "홀 마감", text: "쓰레기통 비우기" },
  { id: 80, step: 7, category: "매장정산", subCategory: "홀 마감", text: "정수기 주변 대기실 물컵 정리" },
  { id: 81, step: 7, category: "매장정산", subCategory: "홀 마감", text: "대기실 의자 정돈 및 상황실 책상 정리" },
  { id: 82, step: 7, category: "매장정산", subCategory: "홀 마감", text: "손님 슬리퍼 신발장에 정리" },
  { id: 83, step: 7, category: "매장정산", subCategory: "쓰레기 비우기", text: "모든 쓰레기 모아서 버릴 때 음식물 필수 확인" },
  { id: 84, step: 7, category: "매장정산", subCategory: "쓰레기 비우기", text: "꽉 찬 쓰레기통 비닐 교체 후 대문 밖에 버리기" },
  { id: 85, step: 7, category: "매장정산", subCategory: "매출 정산", text: "포스기 현금 시재 정산 및 확인" },
  { id: 86, step: 7, category: "매장정산", subCategory: "매출 정산", text: "카드 매출 전표 확인 및 대조" },
  { id: 87, step: 7, category: "매장정산", subCategory: "매출 정산", text: "카드 단말기 전원 종료" },
  { id: 88, step: 7, category: "매장정산", subCategory: "홀 마감", text: "사물함(캐비닛) 충전기 선 뽑기 및 분실물 체크" },
  { id: 89, step: 7, category: "매장정산", subCategory: "다음날 구글시트", text: "구글 시트 다음 날짜로 복제 및 이름 변경" },
  { id: 90, step: 7, category: "매장정산", subCategory: "다음날 구글시트", text: "시트 내 날짜/요일 수정" },
  { id: 91, step: 7, category: "매장정산", subCategory: "다음날 구글시트", text: "남은 대기 예약 상황 시트로 이관" },
  { id: 92, step: 7, category: "매장정산", subCategory: "다음날 구글시트", text: "다음날 예약자 안내 문자 발송" },
  { id: 93, step: 7, category: "매장정산", subCategory: "노트북 사진정리", text: "오늘 날짜의 사진 폴더 생성" },
  { id: 94, step: 7, category: "매장정산", subCategory: "노트북 사진정리", text: "촬영된 사진 폴더로 이동 후 기존 컴퓨터 내 원본 삭제" },
  { id: 95, step: 7, category: "매장정산", subCategory: "노트북 사진정리", text: "포토샵 템플릿 날짜 익일로 변경 후 저장" },

  // --- 8단계: 최종 최종 마감 ---
  { id: 96, step: 8, category: "최종보안", subCategory: "PC/CCTV 종료", text: "상황실 CCTV 모니터 및 녹화기 종료 (총 2개)" },
  { id: 97, step: 8, category: "최종보안", subCategory: "PC/CCTV 종료", text: "상황실 메인 컴퓨터 2대 전원 끄기" },
  { id: 98, step: 8, category: "최종보안", subCategory: "PC/CCTV 종료", text: "카운터/홀 컴퓨터 1대 전원 끄기" },
  { id: 99, step: 8, category: "최종보안", subCategory:"전력차단", text: "비폴로 , 화장실 2개 차단기 내리기" },
  { id: 100, step: 8, category: "최종보안", subCategory: "시설 잠금", text: "화장실 문 및 창고 문 완전히 닫혔는지 체크" },
  { id: 101, step: 8, category: "최종보안", subCategory: "출퇴근", text: "마감 근태찍기" },
  { id: 102, step: 8, category: "최종보안", subCategory: "전체 소등", text: "홀 메인 조명등 및 간접 매장 등 전체 소등" },
  { id: 103, step: 8, category: "최종보안", subCategory: "시설 잠금", text: "매장 바깥 유리문/셔터 최종 잠금 장치 확인" }
];